COMMON DEF Raw2Float%(H%,L%)
 VAR B%=H%>>20AND 4095,BM$=BIN$(H%AND 1048575,20)+BIN$(L%,32),I%,LN%=52,NF#=0.0
 IF(B%AND 2047)==&H7FFTHEN
  IF H%AND 1048575THEN RETURN NaN#*SGN(H%)
  RETURN Inf#*SGN(H%)
 ENDIF
 B%=(B%AND 2047)-&H3FF
 NF#=0
 WHILE I%<LN%
 IF BM$[I%]=="1"THEN INC NF#,POW(2,-1-I%)
 INC I%WEND
 NF#=POW(2,B%)+NF#*POW(2,B%)
 RETURN NF#
END
COMMON DEF Float2Raw F# OUT H%,L%
 VAR B%,LB%=52,S$,NF#,BS% : H%=0 L%=0
 IF F#==0THEN RETURN
 IF CLASSIFY(F#)!=0THEN
  H%=&H7FF00000+&HF0000*(CLASSIFY(F#)==2)
  RETURN
 ENDIF
 B%=FLOOR(LOG(ABS(F#),2))
 IF F#<0THEN
 BS%=&HBFF+B%
 IF ABS(B%)>1000THEN F#=F#*POW(2,-500*SGN(B%))B%=B%-500*SGN(B%)
 NF#=(ABS(F#)*POW(2,-B%))*2-2
 ELSE
 BS%=&H3FF+B%
 IF ABS(B%)>1000THEN F#=F#*POW(2,-500*SGN(B%))B%=B%-500*SGN(B%)
 NF#=F#*POW(2,-B%)*2-2
 ENDIF
 WHILE LB%INC S$,"01"[FLOOR(NF#)>=1]
 IF NF#>=1THEN DEC NF#
 NF#=NF#*2DEC LB%WEND
 S$=BIN$(BS%,12)+S$
 H%=VAL("&B"+MID$(S$, 0,32))
 L%=VAL("&B"+MID$(S$,32,32))
END
COMMON DEF ASC2INT_LE%(S$,L%)
 VAR T$=S$+NIL$*(L%-LEN(S$))
 IF L%==4THEN
  RETURN ASC(T$[3])<<24OR(ASC(T$[2])AND 255)<<16OR(ASC(T$[1])AND 255)<<8OR(ASC(T$[0])AND 255)
 ELSEIF L%==2THEN
  RETURN ASC(T$[1])<<16OR ASC(T$[0])
 ELSEIF L%==1THEN
  RETURN ASC(T$)
 ENDIF
 RETURN 0
END
COMMON DEF INT2ASC_LE$(I%,L%)
 IF L%==4THEN
  RETURN CHR$(I%AND 255)+CHR$(I%>>8AND 255)+CHR$(I%>>16AND 255)+CHR$(I%>>24AND 255)
 ELSEIF L%==2THEN
  RETURN CHR$(I%)+CHR$(I%>>16)
 ELSEIF L%==1THEN
  RETURN CHR$(I%)
 ENDIF
 RETURN""
END
COMMON DEF STR2ARR%(S$,CW%)
 DIM A%[0],B%,L%=LEN(S$)*CW%
 WHILE B%<L%
  IF(B%MOD CW%)THEN SETBYTEA B%,ASC(S$[B%DIV CW%])>>8,A%
  IF!(B%MOD CW%)THEN SETBYTEA B%,ASC(S$[B%DIV CW%]),A%
 INC B%WEND
 RETURN A%
END
COMMON DEF ARR2STR$(A%,CW%,SL%)
 DIM S$,C%,B%,CB%,I%,L%=LEN(A%)
 IF SL%<1THEN SL%=INTMX%
 WHILE I%<L%
  B%=0WHILE B%<4
   C%=C%OR((A%[I%]>>(B%*8))AND 255)<<(CB%*8)
   CB%=(CB%+1)MOD CW%
   IF!CB%THEN INC S$,CHR$(C%)C%=0
  INC B%WEND
 INC I%WEND
 RETURN LEFT$(S$,SL%)
END
COMMON DEF GETBITA(B%,D%)
 IF LEN(D%)*32<=B%THEN EXPANDBITA D%,B%+1
 RETURN D%[B%DIV 32]>>(B%MOD 32)AND 1
END
COMMON DEF SETBITA B%,V%,D%
 IF LEN(D%)*32<=B%THEN EXPANDBITA D%,B%+1
 D%[B%DIV 32]=D%[B%DIV 32]AND NOT(1<<(B%MOD 32))OR((V%AND 1)<<(B%MOD 32))
END
DEF EXPANDBITA D%,B%
 WHILE LEN(D%)*32<B%PUSH D%,0WEND
END
COMMON DEF GETBYTEA(B%,D%)
 IF LEN(D%)*4<=B%THEN EXPANDBYTEA D%,B%+1
 RETURN D%[B%DIV 4]>>((B%MOD 4)*8)AND 255
END
COMMON DEF SETBYTEA B%,V%,D%
 IF LEN(D%)*4<=B%THEN EXPANDBYTEA D%,B%+1
 D%[B%DIV 4]=D%[B%DIV 4]AND NOT(255<<((B%MOD 4)*8))OR((V%AND 255)<<((B%MOD 4)*8))
END
DEF EXPANDBYTEA D%,B%
 WHILE LEN(D%)*4<B%PUSH D%,0WEND
END
COMMON DEF ARRAY1%(S)DIM _%[S]RETURN _%END
COMMON DEF ARRAY1#(S)DIM _#[S]RETURN _#END
COMMON DEF ARRAY1$(S)DIM _$[S]RETURN _$END
COMMON DEF ARRAY2%(X,Y)DIM _%[X,Y]RETURN _%END
COMMON DEF ARRAY2#(X,Y)DIM _#[X,Y]RETURN _#END
COMMON DEF ARRAY2$(X,Y)DIM _$[X,Y]RETURN _$END
COMMON DEF ARRAY3%(X,Y,Z)DIM _%[X,Y,Z]RETURN _%END
COMMON DEF ARRAY3#(X,Y,Z)DIM _#[X,Y,Z]RETURN _#END
COMMON DEF ARRAY3$(X,Y,Z)DIM _$[X,Y,Z]RETURN _$END
COMMON DEF ARRAY4%(X,Y,Z,W)DIM _%[X,Y,Z,W]RETURN _%END
COMMON DEF ARRAY4#(X,Y,Z,W)DIM _#[X,Y,Z,W]RETURN _#END
COMMON DEF ARRAY4$(X,Y,Z,W)DIM _$[X,Y,Z,W]RETURN _$END
COMMON DEF CYFS_STrim$(STR$)VAR L%=LEN(STR$)
VAR S$,I%,B$=" "WHILE I%<L%&&STR$[I%]<=B$INC I%WEND
S$=RIGHT$(STR$,L%-I%)DEC L%,I%+1
WHILE L%>=0&&S$[L%]<=B$DEC L%EAT POP(S$)WEND
RETURN S$END
COMMON DEF FromUTF8$(A$)
 VAR R$,I%,L%=LEN(A$)
 WHILE I%<L%
  VAR B$=A$[I%],B%=ASC(B$)
  IF B%>=&HF0&&I%+3<L%THEN
   B%=(B%AND 7)<<6OR(ASC(A$[I%+1])AND&H3F)
   B%=B%<<6OR(ASC(A$[I%+2])AND&H3F)
   B%=B%<<6OR(ASC(A$[I%+3])AND&H3F)
   DEC B%,65536
   INC R$,CHR$(&HD800+(B%>>10))
   INC R$,CHR$(&HDC00+(B%AND&H3FF))
   INC I%,3
  ELSEIF B%>=&HE0&&I%+2<L%THEN
   B%=B%AND&H0F
   B%=B%<<6OR(ASC(A$[I%+1])AND&H3F)
   B%=B%<<6OR(ASC(A$[I%+2])AND&H3F)
   INC R$,CHR$(B%)INC I%,2
  ELSEIF B%>=&HC2&&I%+1<L%THEN
   B%=B%AND&H1F
   B%=B%<<6OR(ASC(A$[I%+1])AND&H3F)
   INC R$,CHR$(B%)INC I%
  ELSE
   INC R$,B$
  ENDIF
  INC I%
 WEND
 RETURN R$
END
COMMON DEF ToUTF8$(A$)
 VAR I%,R$="",L%=LEN(A$)
 WHILE I%<L%
  VAR B$=A$[I%],B=ASC(B$)
  IF B<=&H7F THEN
   INC R$,B$
  ELSEIF B<=&H7FF THEN
   INC R$,CHR$(&HC0+(B>>6AND&H1F))
   INC R$,CHR$(&H80+(B   AND&H3F))
  ELSE
   IF&HD800<=B&&B<=&HDBFF&&I%<L%THEN
    VAR B2=ASC(A$[I%+1])
    IF &HDC00<=B2&&B2<=&HDFFF THEN
     B=((B AND&H3FF)<<10)+(B2 AND&H3FF)
     INC B,&H10000
     INC R$,CHR$(&HF0+(B>>18AND&H07))
     INC R$,CHR$(&H80+(B>>12AND&H3F))
     INC R$,CHR$(&H80+(B>>6 AND&H3F))
     INC R$,CHR$(&H80+(B    AND&H3F))
     INC I%CONTINUE
    ENDIF
   ENDIF
   INC R$,CHR$(&HE0+(B>>12AND&H0F))
   INC R$,CHR$(&H80+(B>>6 AND&H3F))
   INC R$,CHR$(&H80+(B    AND&H3F))
  ENDIF
  INC I%
 WEND
 RETURN R$
END